### PR TITLE
Posting comments + hocs refactoring

### PR DESCRIPTION
**Pull request by alexeuler**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-native-tutorial/17)

### CODE REVIEW

**Comment by justin808** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/components/Button/Button.js, line 7 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xCJhUAFYIrVxrVMy:-KM_xCJiEmaQJjvpfRvQ:1580925989) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/Button.js#L7)):_

> ``` JavaScript
> const Wrapper = Platform.OS === 'android' ? TouchableNativeFeedback : TouchableHighlight;
> 
> const Button = ({ onPress, text }) => (
> ```

Should we have flow annotations here? @robwise?

---

_[app/components/Button/ButtonStyle.js, line 11 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xaYbmWAP9RKXHTVM:-KM_xaYbmWAP9RKXHTVN:-1368484757) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/ButtonStyle.js#L11)):_

> ``` JavaScript
> };
> 
> export default styles;
> ```

@robwise @alleycat-at-git, I can see this pattern for functions, so we get a name.

Should the `export default` go on top?

or a good pattern for always having the default be the last line so easy to scan?

---

_[app/hocs/withAddCommentHandlers.js, line 4 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa1M_ygZGEQHJxKOGV:-KMa1M_ygZGEQHJxKOGW:1730096941) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withAddCommentHandlers.js#L4)):_

> ``` JavaScript
> import _ from 'lodash/fp';
> 
> const withAddCommentHandlers = Component => class extends React.Component {
> ```

@robwise do you agree with using a HOC here to keep the Component logic separate from the async redux interactions?

---

_[app/hocs/withAddCommentHandlers.js, line 21 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa0p7L-RDHFefCrU2p:-KMa0p7L-RDHFefCrU2q:-1615186225) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withAddCommentHandlers.js#L21)):_

> ``` JavaScript
>   addComment() {
>     this.props.actions.submitCommentRequest(this.props.getState());
>     this.props.navigator.pop();
> ```

this should be done from the redux-saga so that pop only happens if success or else we display an error

---

_[app/hocs/withRemoteDataSource.js, line 25 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_zojCzztaevGuIkoO:-KM_zojCzztaevGuIkoP:166902) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withRemoteDataSource.js#L25)):_

> ``` JavaScript
> 
>   componentWillReceiveProps(nextProps) {
>     this.setState({ dataSource: this.state.dataSource.cloneWithRows(selector(nextProps)) });
> ```

[

---

_[app/sagas/submitComment.js, line 11 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa2vDsrSQmZLvLrOG2:-KMa2vDsrSQmZLvLrOG3:1281821387) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/sagas/submitComment.js#L11)):_

> ``` JavaScript
>     const { comment, error } = yield call(() => responsePromise.json());
>     if (error) throw error;
>     yield put({ type: actionTypes.SUBMIT_COMMENT_SUCCESS, comment });
> ```

We can have the add comment screen watch for the change to the isSaving and then change the navigation, rather than just doing it when the save button is pressed.

``` js
  [actionTypes.SUBMIT_COMMENT_SUCCESS]($$state: $$Map, action: { comment: String }) {
    return $$state.withMutations(state => (
      state
        .updateIn(
          ['$$comments'],
          $$comments => $$comments.unshift(Immutable.fromJS(action.comment))
        )
        .merge({
          submitCommentError: null,
          isSaving: false,
        })
    ));
  },
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17)_

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/components/Button/Button.js, line 7 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xCJhUAFYIrVxrVMy:-KMaeu9b3BTy1odg46Jk:-278243248) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/Button.js#L7)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> Should we have flow annotations here? @robwise?
> </details>
> @justin808 Alex and I aren't sure what we want to do as far as that goes, it's my understanding from reading the Facebook React team's meeting minutes that internally they are switching to using Flow annotations instead of PropTypes. The advantage is you can use flow static type checking to verify your components are set up correctly, whereas PropTypes only check at runtime and may not catch edge cases the way static analysis can. Also, @alexfedoseev has reported some performance concerns with large amounts of PropType validations. However, as I said, we haven't come to some sort of official stance on this. So in the meantime, I've got both on my components in the GLM stuff.

---

_[app/components/Button/ButtonStyle.js, line 11 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xaYbmWAP9RKXHTVM:-KMagmHkvZ9rY7GgmMCY:-1894348298) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/ButtonStyle.js#L11)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> @robwise @alleycat-at-git, I can see this pattern for functions, so we get a name.
> 
> Should the `export default` go on top?
> 
> or a good pattern for always having the default be the last line so easy to scan?
> </details>
> I would have just done it inline yeah. Also FYI, you can do `export default function myNamedFunction() { return; };` to get inlined, named functions

---

_[app/hocs/withAddCommentHandlers.js, line 4 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa1M_ygZGEQHJxKOGV:-KMahIrKZKWHqSO6Rsx7:631763838) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withAddCommentHandlers.js#L4)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> @robwise do you agree with using a HOC here to keep the Component logic separate from the async redux interactions?
> </details>
> @justin808 no, but @alexfedoseev disagrees. IMO HOC should be for reusable and composable abstractions, not one-off concretions

---

_[app/hocs/withAddCommentHandlers.js, line 21 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa0p7L-RDHFefCrU2p:-KMai1uND5ZnwAElCTVu:-686309131) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withAddCommentHandlers.js#L21)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> this should be done from the redux-saga so that pop only happens if success or else we display an error
> </details>
> if you do that, you could probably actually turn this entire thing into an SFC, which means you can just have the entire thing inline in the base component in the first place, and delete this file (unless I'm overlooking something)

---

_[app/sagas/submitComment.js, line 11 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa2vDsrSQmZLvLrOG2:-KMaiOxTiznkOqcg_d_O:-465856368) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/sagas/submitComment.js#L11)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> We can have the add comment screen watch for the change to the isSaving and then change the navigation, rather than just doing it when the save button is pressed.
> 
> ``` js
>   [actionTypes.SUBMIT_COMMENT_SUCCESS]($$state: $$Map, action: { comment: String }) {
>     return $$state.withMutations(state => (
>       state
>         .updateIn(
>           ['$$comments'],
>           $$comments => $$comments.unshift(Immutable.fromJS(action.comment))
>         )
>         .merge({
>           submitCommentError: null,
>           isSaving: false,
>         })
>     ));
>   },
> ```
> 
> </details>
> agree with @justin808 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17)_

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/components/Button/Button.js, line 7 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xCJhUAFYIrVxrVMy:-KMatfJFjQW_urqCSZVZ:839718680) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/Button.js#L7)):_
<details><summary>

<i>Previously, robwise (Rob Wise) wrote…</i></summary>



> @justin808 Alex and I aren't sure what we want to do as far as that goes, it's my understanding from reading the Facebook React team's meeting minutes that internally they are switching to using Flow annotations instead of PropTypes. The advantage is you can use flow static type checking to verify your components are set up correctly, whereas PropTypes only check at runtime and may not catch edge cases the way static analysis can. Also, @alexfedoseev has reported some performance concerns with large amounts of PropType validations. However, as I said, we haven't come to some sort of official stance on this. So in the meantime, I've got both on my components in the GLM stuff.
> </details>
> Belt and suspenders, @robwise. I like that, especially with tests for security!

What is the code here if we add flow? 

---

_[app/components/Button/ButtonStyle.js, line 11 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xaYbmWAP9RKXHTVM:-KMatqa1qkSVcgjfGzUC:1566255466) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/ButtonStyle.js#L11)):_
<details><summary>

<i>Previously, robwise (Rob Wise) wrote…</i></summary>



> I would have just done it inline yeah. Also FYI, you can do `export default function myNamedFunction() { return; };` to get inlined, named functions
> </details>
> and 

``` js
export default const foobar = baz => "abc";
```

right?

Anyway, I'm OK with putting at the bottom to make it simple, but it's a bit redundant. I'm OK either way. Maybe this is a shades of green for the bike shed discussion?

---

_[app/hocs/withAddCommentHandlers.js, line 4 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa1M_ygZGEQHJxKOGV:-KMauD8e8w4gRC05ASin:1785798593) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withAddCommentHandlers.js#L4)):_
<details><summary>

<i>Previously, robwise (Rob Wise) wrote…</i></summary>



> @justin808 no, but @alexfedoseev disagrees. IMO HOC should be for reusable and composable abstractions, not one-off concretions
> </details>
> I think having a HOC here definitely makes this harder to understand at first if you're not used to the pattern. I can be swayed either way.

---

_[app/hocs/withAddCommentHandlers.js, line 21 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa0p7L-RDHFefCrU2p:-KMauNbKvsV67bpuE_Iq:1983869137) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withAddCommentHandlers.js#L21)):_
<details><summary>

<i>Previously, robwise (Rob Wise) wrote…</i></summary>



> if you do that, you could probably actually turn this entire thing into an SFC, which means you can just have the entire thing inline in the base component in the first place, and delete this file (unless I'm overlooking something)
> </details>
> @robwise I'll show you once I get the next part done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17)_

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/components/Button/Button.js, line 7 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xCJhUAFYIrVxrVMy:-KMaw9dN9qEq_xLVDDOp:-1318923623) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/Button.js#L7)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> Belt and suspenders, @robwise. I like that, especially with tests for security!
> 
> What is the code here if we add flow? 
> </details>
> @justin808 well that's the nice thing about converting, because if you already have propTypes it makes it trivial to figure out what annotations you should add. Here's with flow annotations.

``` js
// @flow
import React, { PropTypes } from 'react';
import { View, Text, Platform, TouchableHighlight, TouchableNativeFeedback } from 'react-native';
import styles from './ButtonStyle';
 
const Wrapper = Platform.OS === 'android' ? TouchableNativeFeedback : TouchableHighlight;
 
const Button = ({ onPress, text }: {onPress: Function, text: string}) => (
  <Wrapper onPress={onPress}>
    <View>
      <Text style={styles.text}>{text}</Text>
    </View>
  </Wrapper>
);
 
Button.propTypes = {
  onPress: PropTypes.func,
  text: PropTypes.string,
};
 
export default Button;
```

 notice how we have to define the entire object over again because we are destructuring (see [this issue](https://github.com/facebook/flow/issues/235) if you really care). You can also use `type` declarations which are nice for readability:

``` js
// ...
type Props = {onPress: Function, text: string};
 
const Button = ({ onPress, text }: Props) => (
  //...
```

---

_[app/components/Button/ButtonStyle.js, line 11 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KM_xaYbmWAP9RKXHTVM:-KMavbkZrs5yA1TKDjTE:1567533873) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/components/Button/ButtonStyle.js#L11)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> and 
> 
> ``` js
> export default const foobar = baz => "abc";
> ```
> 
> right?
> 
> Anyway, I'm OK with putting at the bottom to make it simple, but it's a bit redundant. I'm OK either way. Maybe this is a shades of green for the bike shed discussion?
> </details>
> @justin808 no that one won't work believe it or not. Yeah sort of bike shed, but I don't mind bike shed discussions lol

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17)_

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[app/hocs/withAddCommentHandlers.js, line 4 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17#-KMa1M_ygZGEQHJxKOGV:-KMaym4acBYB7U6wqf4u:-1602356080) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/edc11c9a0ab99f3d435327878993b08ee9c33079/app/hocs/withAddCommentHandlers.js#L4)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> I think having a HOC here definitely makes this harder to understand at first if you're not used to the pattern. I can be swayed either way.
> </details>
> Yeah I feel same way

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/17)_

**Pull request merged**
