### PR TITLE
refactoring actions and add commentsActionCreator test

### PR DESCRIPTION
**Pull request by dansjensen**
Suggested improvements.

---

This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-native-tutorial/8)

### CODE REVIEW

**Comment by justin808** [comment]
Some things to fix...

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/actions/commentsActionCreators.js, line 5 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMGx_KSkSScOb1xsNU:-KMMGx_KSkSScOb1xsNV:141730899) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/app/actions/commentsActionCreators.js#L5)):_

> ``` JavaScript
> 
> export const setIsFetching = () => ({
>   type: actionTypes.SET_IS_FETCHING,
> ```

Let's not change the code to use fat arrows.

By using fat arrows, we're doing an implicit "this" binding, per [this explanation](http://exploringjs.com/es6/ch_arrow-functions.html).

---

_[test/actions/commentsActionCreators.spec.js, line 6 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMHQZgl_RQ9xr6fjyw:-KMMHQZgl_RQ9xr6fjyx:-612639312) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/test/actions/commentsActionCreators.spec.js#L6)):_

> ``` JavaScript
> 
> describe('commentsActionCreators', () => {
>   it('setIsFetching should create SET_IS_FETCHING action', () => {
> ```

Please use functions, as chai does not want an implicit this binding: [reference](https://mochajs.org/#arrow-functions).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-:-KMMIMLPHDA8eL027Unc:945969162)_

**Comment by robwise** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/actions/commentsActionCreators.js, line 5 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMGx_KSkSScOb1xsNU:-KMN8Tm5lR0wbdxFMoIJ:441096895) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/app/actions/commentsActionCreators.js#L5)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> Let's not change the code to use fat arrows.
> 
> By using fat arrows, we're doing an implicit "this" binding, per [this explanation](http://exploringjs.com/es6/ch_arrow-functions.html).
> </details>
> many devs these days are using fat arrows simply for their terse syntax regardless of whether they need to bind `this`, especially since it's sort of an anti-pattern now to rely on `this` anyway since it leads to many bugs. Abramov himself wrote his action creators this way in his Egghead tutorials

---

_[test/actions/commentsActionCreators.spec.js, line 6 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMHQZgl_RQ9xr6fjyw:-KMN8tgETPct1jWASUYp:684437767) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/test/actions/commentsActionCreators.spec.js#L6)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> Please use functions, as chai does not want an implicit this binding: [reference](https://mochajs.org/#arrow-functions).
> </details>
> it's mocha saying that, not chai, but I write them this way and haven't had a problem so far, but it's up to you guys obviously

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8)_

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[app/actions/commentsActionCreators.js, line 5 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMGx_KSkSScOb1xsNU:-KMNRyLgFdMJusheXyb0:552196430) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/app/actions/commentsActionCreators.js#L5)):_
<details><summary>

<i>Previously, robwise (Rob Wise) wrote…</i></summary>



> many devs these days are using fat arrows simply for their terse syntax regardless of whether they need to bind `this`, especially since it's sort of an anti-pattern now to rely on `this` anyway since it leads to many bugs. Abramov himself wrote his action creators this way in his Egghead tutorials
> </details>
> @robwise another reason, which may or may no longer be valid, is whether the function names shows in stack dumps or as anonymous.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8)_

**Comment by alexeuler** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[app/actions/commentsActionCreators.js, line 5 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMGx_KSkSScOb1xsNU:-KMOaU7L5OQXP6wh8PeL:908808058) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/app/actions/commentsActionCreators.js#L5)):_
<details><summary>

<i>Previously, justin808 (Justin Gordon) wrote…</i></summary>



> @robwise another reason, which may or may no longer be valid, is whether the function names shows in stack dumps or as anonymous.
> </details>
> I'm agree with @Rob and will vote for arrow functions too just because it have a simple syntax. BTW the stack trace prints good.
> 

---

_[test/actions/commentsActionCreators.spec.js, line 1 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMOdlksPk71lX-MMe6Z:-KMOdlksPk71lX-MMe6_:-1215302162) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/test/actions/commentsActionCreators.spec.js#L1)):_

> ``` JavaScript
> import { expect } from 'chai';
> ```

I'm not sure, that we really need this test, because there's only one chance to fail this test - remove the action from the action types. But that just will add additional boilerplate each time we change out actions structure. The kind tests I would expect to present is `state + action = new state`. But I'm not sure about this one, since we always have debates about the testing approaches. @robwise @justin808 what do you think?

---

_[test/actions/commentsActionCreators.spec.js, line 6 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMHQZgl_RQ9xr6fjyw:-KMOdnpNA24yXqlsx8RZ:-1731794185) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/test/actions/commentsActionCreators.spec.js#L6)):_
<details><summary>

<i>Previously, robwise (Rob Wise) wrote…</i></summary>



> it's mocha saying that, not chai, but I write them this way and haven't had a problem so far, but it's up to you guys obviously
> </details>
> Another approach is to use arrows, but be careful about mocha context the way Rob does it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8)_

**Comment by robwise** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[test/actions/commentsActionCreators.spec.js, line 1 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMOdlksPk71lX-MMe6Z:-KMQC-AHheUaGVQ7b_z2:1554140748) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/test/actions/commentsActionCreators.spec.js#L1)):_
<details><summary>

<i>Previously, alleycat-at-git (Alexey) wrote…</i></summary>



> I'm not sure, that we really need this test, because there's only one chance to fail this test - remove the action from the action types. But that just will add additional boilerplate each time we change out actions structure. The kind tests I would expect to present is `state + action = new state`. But I'm not sure about this one, since we always have debates about the testing approaches. @robwise @justin808 what do you think?
> </details>
> It feels unsafe not to test it, but then when you write the test, you realize the test seems very silly, so I stopped writing them, personally. I can see both sides though

---

_[app/actions/commentsActionCreators.js, line 5 [r1]](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8#-KMMGx_KSkSScOb1xsNU:-KMQCIGIsBAWpgfgzaWj:-1887169268) ([raw file](https://github.com/shakacode/react-native-tutorial/blob/005716ea1fd1239a24f91d7daa439ad47885bb5f/app/actions/commentsActionCreators.js#L5)):_

> whether the function names shows in stack dumps or as anonymous.

Babel implemented the feature Alexey demonstrates above a couple of months ago. That is, if you are assigning the fat arrow function to a constant, it assigns that constant's name to the function in the stack trace. 

You can still end up with an anonymous in the stack trace if you don't assign to a constant (such as when making a callback inline inside a function call). This was a big problem when we didn't have our source maps set up right and Babel hadn't implemented this functionality yet, but now it's less so.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-native-tutorial/8)_

**Comment by justin808** [comment]
Closing this PR. 
- I merged in the comment to the README.md.
- Not doing the test example as that test doesn't verify much.
- Creating the actions is done differently in a later PR from @alleycat-at-git.

**Pull request closed without merging**
